### ISSUE TITLE
When viewing a zombie text give user an option to see detailed list of text transformations 

### ISSUE THREAD

**Issue by flashashen** [flashashen/zombiepoetryproject#1]
the transformations are already being captured. if they were sent by the nlp server in the response, then the site could save them as metadata and display. Here is a sample of the transformations

> MutateReplaceChildrenFromProgenitor{percentageChomped=60, patternTargetString='NP (< SBAR | < NN | < NNS )'}
> - replace [some years ] with [a family ]
> - replace [nothing ] with [the car ]
> - replace [shore ] with [time ]
> - replace [the watery part ] with [a girl 's ]
> - replace [the world ] with [roads ]
> - replace [a way I have of driving off the spleen , and regulating the circulation ] with [mind ]
> - replace [the circulation ] with [the convenience store ]
> - replace [my soul ] with [burgers ]
> - replace [the rear ] with [the girl ]
> - replace [every funeral I meet ] with [a teacher ]
> - replace [my hypos ] with [fantasies ]
> - replace [such an upper hand ] with [columns ]
> - replace [a strong moral principle ] with [the mind , which no one needs ]
> - replace [the street ] with [the front ]
> - replace [people 's hats ] with [a grill ]
> - replace [people 's ] with [horizon ]
> - replace [my substitute ] with [a whole crew ]
> - replace [pistol and ball ] with [your journey ]
> - replace [his sword ] with [a burger ]
> - replace [the ship ] with [the taste ]
> - replace [all men ] with [a spit-shined china dish ]
> - replace [some time ] with [the mind , which no one needs ]
> - replace [nearly the same feelings ] with [that couch ]
> - replace [the ocean ] with [the high school , which he points out ]
> 
> MutateSimpleReplaceFromProgenitor{percentageChomped=60, patternTargetString='VBG'}
> - replace [having] with [surviving]
> - replace [pausing] with [stitching]
> - replace [bringing] with [turning]
> - replace [stepping] with [mending]
> - replace [knocking] with [showing]
> 
> MutateSimpleReplaceFromProgenitor{percentageChomped=60, patternTargetString='VBD'}
> 
> MutateSimpleReplaceFromProgenitor{percentageChomped=40, patternTargetString='RB | RBR | RBS'}
> - replace [ago] with [almost]
> - replace [precisely] with [even]
> - replace [methodically] with [right]
> - replace [then] with [sometimes]
> - replace [as] with [now]
> - replace [almost] with [not]
> - replace [very] with [ahead]
> 
> MutateSimpleReplaceFromProgenitor{percentageChomped=40, patternTargetString='JJ | JJR | JJS'}
> - replace [little] with [best]
> - replace [drizzly] with [sad]
> - replace [high] with [free]
> - replace [whole] with [African-American]
> 
> MutateReplaceFragFromSignatureZombieFrags{percentageChomped=50, patternTargetString='__ < FRAG'}
> - replace [mind how long even ] with [Movement.]

**Comment by multiverse15** [comment]
I like this idea, especially if we could spruce up the presentation a bit. Would we link to the symbol that separates victim from zombie on the Incidents page or would this be its own page? We mentioned once the possibility of using the symbol to link to interesting visuals of the process...the user hovers over or clicks the symbol to see something of the process...

Nice work, boy!

**Comment by flashashen** [comment]
I was working last night and i realized that I keep getting lost in contemplation about the grammar corrections and parsing. The languagetool refused to provide anything useful. So the solutions are grammar are probably varied and involved. I’m eager to do that kind of work but I keep re-arriving at user-interaction and the display of nlp artifacts as the silver bullets - uh wrong analogy. Sorry to keep vacillating. Having these elements will also be useful for improving the grammar later. So the interactions will evolve but, yes, I was thinking of just popping up some info when hovering/clicking the symbol - just as a start. And the selective re-zombify is harder but would be killer for producing zombies. Ill create separate issues for that.

**Comment by flashashen** [comment]
the mutations are stored per sentence now so we could display when hovering over a sentence. or when clicking on a sentence option to re-zombify or to view aritfacts like this could pop up. But maybe we should just stick with the hover over the arrow for first release

**Comment by multiverse15** [comment]
Hover over the arrow sounds good for first release, I think.

**Comment by flashashen** [comment]
first cut of this is ready. it works on infection page only so far but should be straightforward to use on incidents page also. Changed the ui a bit in the zombie text area of infection page. Pushing up to test site now. interested in comments.

**Comment by multiverse15** [comment]
It looks fantastic! I love that it so artfully demarks the sentence portion, but doesn't obscure above and below, since one of the goals of re-zombifying is often to "fit" a sentence portion thematically with what's before and after. 

I was disappointed about the mobile appearance you reported, but double-click to re-zombify and leaving the "I" button works for me!  (Already incorporated new language on production site.)

**Comment by flashashen** [comment]
i think we're good for now on this. closing
