### ISSUE TITLE
last line

### ISSUE THREAD

**Issue by multiverse15** [flashashen/zombiepoetryproject#10]
Just to confirm what we discussed yesterday: For the last line, roll the dice to zombify, but if it fails to do so, substitute in a fragment at 100%. 

Also, would it be possible to match the character count of the last line to the penultimate one? My thinking is that for the last line, a large variation either way looks strange...

**Comment by flashashen** [comment]
i'm not seeing a last line issue. the last line is being transformed normally in my testing just now. i did add the frag substitution at 100% for any explicitly rezombified sentence. 

About the special logic for the last line length, where did we leave that?

**Comment by multiverse15** [comment]
I bet the 100% fragment solves a lot!

In terms of the last line. Since we're lineating anyway, can we tie the line length of the last line to the line above it in some way to avoid a great discrepancy? The rare times the last line is either very short or very long, it undercuts the lineation.

**Comment by flashashen** [comment]
from other convo: 

Find some way of ensuring last line of zombie poem doesn't go extremely long or cut off extremely short. (Tie to penultimate line?)

I will look at a re-lineation scheme that looks back a few sentences. this could be something to enhance the whole poem..  running out of time for the fancy frontend footwork i was dreaming of

**Comment by flashashen** [comment]
so the first pass of re-lineation is done. The original line break algorithm still does it's thing as before, but now a 'smoothing' is applied afterwards to address large differences in adjacent line length. There was significant ground work required to get this far but I realize that this doesn't address the last line directly, and in some tests just now the last line suffers as much as ever. If the last line does need attention, I now have a tool to deal with it.

**Comment by flashashen** [comment]
the smoothing doesn't currently apply the same line break rules. It will choose weak words. To correct this I just utilize and extend a bit the scoring mechanism that is already in place. This will lower the effectiveness of the smoothing so it's just a matter of preference and time at this point

**Comment by multiverse15** [comment]
Okay, I think I understand. Time allowing, let's aim for a middle ground between relatively consistent line length and end words, erring in favor of consistent line length and relaxing eligible end words as much as necessary. If memory serves, we originally restricted pronouns and two-letter verbs, yes? If so, they both could be brought back in as eligible end words Certainly, there is enough flexibility in contemporary practice to support this! Excellent work!!!

**Comment by flashashen** [comment]
smoothing phase 1 is done but refinement and special attention to last line are still needed

**Comment by multiverse15** [comment]
This hasn't been an issue. Perhaps revisit post Phase II
