### ISSUE TITLE
Random capitalization in zombie text.

### ISSUE THREAD

**Issue by flashashen** [flashashen/zombiepoetryproject#13]
this has been looked at a few times but it seems there is still room for improvement even without using the entity recognition method.

**Comment by multiverse15** [comment]
Still seeing this on occasion, mostly now with poetry lineated with capital letters, ie old stuff; older convention.

**Comment by flashashen** [comment]
a few examples of this as they're found would be helpful. i was fishing for them earlier and it wasn't cooperating. Trying to discover the source - is it victim caps or ride-along caps that are getting sub'd in? or now re-lineation might have introduced errors..

**Comment by multiverse15** [comment]
If you're okay with me handling stragglers as curator of Incidents, I think this can be closed for now.
