### ISSUE TITLE
replace challenge question with captcha

### ISSUE THREAD

**Issue by flashashen** [flashashen/zombiepoetryproject#16]
I prefer the current challenge question to captcha but it's prob too easy to bot spam the site without captcha. Also, its actually easier for users to use captcha than google for Juan. We could use a cookie to prevent folks from being prompted twice  

If this is too off-putting then we could wait and see how much of a problem we have. I think there is also an option to require approval for all posts.

**Comment by multiverse15** [comment]
captcha is fine with me. The purposefully weird display of the words actually fits! I like the idea of the cookie, too.
