### ISSUE TITLE
"S" icons and highlighted text in zombie

### ISSUE THREAD

**Issue by multiverse15** [flashashen/zombiepoetryproject#19]
One of my beta testers, who LOVES the overall mechanics, wished that (once he had gone through the zombie poem analyzing mutations and re-zombifying, and had gotten the poem the way he liked) he could maybe click outside the parameters of the poem and have the "s" icons and highlight disappear. That way, he could re-read it as a whole without distractions before submitting to Incidents.

**Comment by flashashen** [comment]
thats a good suggestion. ill think about the best way to do it

**Comment by flashashen** [comment]
this is done. let me know if it's not to Ed's satisfaction. looks like on the test site yet though. next update of the site..
