### ISSUE TITLE
continuous editing of victim queues up zombie transformations 

### ISSUE THREAD

**Issue by flashashen** [flashashen/zombiepoetryproject#2]
after finishing adding periods to a text i watched the zombie text change several times without me doing anything. Some measure should be taken to prevent this. Either prior requests to the server should be canceled when another is sent or they should be throttled

**Comment by multiverse15** [comment]
Is this still an issue? I haven't observe this.

**Comment by flashashen** [comment]
it was a bit artificial - lots of clicks in a short time. i think i won't worry about it for now.

**Comment by multiverse15** [comment]
Agreed.
