### ISSUE TITLE
Verb substituion

### ISSUE THREAD

**Issue by multiverse15** [flashashen/zombiepoetryproject#20]
I've been thinking that, if it's a simple matter now to do, we might slightly increase the percentage of VP substitutions before Sunday. In testing, these, when they do not mutate, carry over a disproportionate retention of victim voice and tone...If at 50, perhaps increase to 60...

**Comment by flashashen** [comment]
will do. what about the mutation re-ordering that i was planning - putting the NP and frags before the simpler single word mutations? we still have time to isolate these changes and let you test. i could run from my laptop. i could do only VP mutations. etc.

**Comment by multiverse15** [comment]
Sure! Absolutely.

**Comment by flashashen** [comment]
this is easy but i missed it. still want the adjustment? any others? I need to provide a general way for you to experiment with the parameters so you can optimize..

**Comment by multiverse15** [comment]
I think so. Just a slight adjustment to the percentage would be sufficient, I think.
