### ISSUE TITLE
Infection Site

### ISSUE THREAD

**Issue by multiverse15** [flashashen/zombiepoetryproject#21]
Rearrange user instructions and advice on Infection Site page. Perhaps right-hand side, upper right corner...Right now it's below and too easy to ignore. #5 #5 @

**Comment by flashashen** [comment]
i could pop up the instructions and then save the fact that user has seen the instructions in the form data. form data gets cached by the browser so a user likely wouldn't have to re-enter for a while. 

i'll try the right column instructions though. is there some text ready?

**Comment by multiverse15** [comment]
Text is on the page now, just below the text box and subsequent zombie draft. Pop up sounds great, but lets do whatever's easiest on you for the moment. We'll likely never stop tinkering with front-end stuff!
