### ISSUE TITLE
ZBlog and Incidents posts

### ISSUE THREAD

**Issue by multiverse15** [flashashen/zombiepoetryproject#22]
Find way to allow separate posts to z blog and to ensure zombie poems are posted along with victim texts on Incidents.

**Comment by flashashen** [comment]
ok. incidents and infection site are both setup with short-code now so those pages can be edited now. blog area will now show only 'Z Blog' posts. this was done simply by by adding a menu type of category.  the path is /category/zblog. with different paths different categories would show up. there is no special query filtering being done.

**Comment by flashashen** [comment]
i think the current solution to this is satisfactory
