### ISSUE TITLE
Margins for Incidents Page

### ISSUE THREAD

**Issue by multiverse15** [flashashen/zombiepoetryproject#24]
Is there any way to expand the margins for the left and right hand columns of the Incidents page, so that the end of lines don't kick so often to the next line...? Not a big deal, purely cosmetic...

**Comment by flashashen** [comment]
let's leave this one open.  i do want to tweak the style for incidents since we were in such a rush saturday night. i'll get to it soon

**Comment by multiverse15** [comment]
Seems resolved.
