### ISSUE TITLE
Save all sentence re-zombifications and allow user final selection among all

### ISSUE THREAD

**Issue by flashashen** [flashashen/zombiepoetryproject#28]
Sometimes a user wishes they could go back to an earlier substitution but it's lost. Accumulate all the substitutions in a session and allow the user to select the best of each sentence before submission

interface:
As soon as there are multiple zombies of a sentence add a side bar to the supplemental dialog. The sidebar will contain a clickable item for each re-zombie. Enumerate like [latest, -, -, first]. When the selection changes update the zombie text dialog so the text shows the new text and lineation as the sidebar items are selected

**Comment by multiverse15** [comment]
I like using the bottom of the text box for this! (This is also Phase II)

**Comment by flashashen** [comment]
done
