### ISSUE TITLE
recognize semi-colons and colons as terminal punctuation in victim analysis

### ISSUE THREAD

**Issue by flashashen** [flashashen/zombiepoetryproject#3]
Long sentences with semi-colons and colons often produce a weird parse. Also, long sentences make the selective re-zombification not selective enough. 

This can probably be done simply with parameters in the standard stanford nlp sentence parser.

Add em-dashes as terminal punctuation also

**Comment by multiverse15** [comment]
Hey Flash,
This is all great, but the more I experiment, the more I want to increase the control for the user. a bit.  In addition to the additional punctuation, which might do more than I'm thinking, how straightforward would it be to have the program identify conjunctions (ands, buts, althoughs, etc) and count off words within a sentence? So, for example, if a sentence were over, say, 10 words, the program would then break it up into multiple re-zombification targets by subordinating and coordinating conjunctions?
Lots of times, I would LOVE what I got in the first half of the sentence, but then have to let it go to re-zombify the problematic second half... 

```
On Friday, April 15, 2016 10:24 PM, flashashen <notifications@github.com> wrote:
```

 Long sentences with semi-colons and colons often produce a weird parse. Also, long sentences make the selective re-zombification not selective enough. This can probably be done simply with parameters in the standard stanford nlp sentence parser.—

**Comment by flashashen** [comment]
two ways to approach the the re-zombification of sentence fragment
- divide sentences parses after initial analysis but before the initial
  zombification. Alll subsequent processing would work as is unchanged. This
  is probably easiest by could complicate later efforts to use other analyses
  besides the parse trees since many are based on sentences as parsed by the
  stanford tool
- leave sentences as they are but determine user intent by determining
  click or selection position within the sentence then transmit this info to
  the server and let the server try to narrow the re-zombification to the
  selected part of the sentence. I like this better, but longer to implement.

**Comment by multiverse15** [comment]
Ah, I understand. I think you&#39;re right about the limitations/future complications of the pre-initial zombification option, but given our now hard deadline (thanks to me) and your new venture (thanks to Dan), perhaps we should go with it.

Presumably, it would be possible to reverse track after going live and pursue the user-selection approach after initial launch, which, if I&#39;m understanding correctly, could potentially allow the user word for word control over re-zombify cation?

Might be another nice innovation for zombie 2.0...

**Comment by flashashen** [comment]
this is ready to look at on the test site. '--' are also being taken as a terminal.

**Comment by multiverse15** [comment]
Testing Thoughts:

The mechanism is REALLY working well with middle-length sentences and longer sentences with grammatically identified clauses (which allow for re-zombification withing sentences)!!! With long sentences, especially with clauses separated by commas, it's often difficult, though not impossible, to get a workable result. 

Would it be possible to allow the user to highlight a phrase within a long sentence that wasn't separated by a semi-colon, colon, or dash in the original, then click the highlighted portion to re-zombify, preserving the rest? For example, say they like the rezombified first and last part of the sentence, but want to rezombify the middle. Right now, unless there were a terminal punctuation marker separating the sentence elements in the original, the whole sentence re-zombifies.

**Comment by flashashen** [comment]
the partial sentence re-zombify is what we discussed before where the
trickiest part is to match the select zombie text to the right part of the
victim parse tree. I think I know how to do it but its a bit involved. its
just a matter of priorities now for the May1st release

**Comment by multiverse15** [comment]
Ah, okay. Not a priority, I think, as I can verbalize the limitations for users on the front-end, along with instructions about standardizing spelling and punctuation.

**Comment by flashashen** [comment]
can do more in phase 2

**Comment by flashashen** [comment]
broke this but now i think it's fixed again.

**Comment by multiverse15** [comment]
Excellent! Roped in Jay as beta tester. I'll talk him through it first, then give him the night. He's using an iPad, so this might also be instructive, re: appearance and usability....
