### ISSUE TITLE
first and last character apostrophes (colloquial contractions) are not treated as part of word

### ISSUE THREAD

**Issue by flashashen** [flashashen/zombiepoetryproject#4]
The apostrophe should not be carried over to smiling' in the zombie text below. Will require tweaking of the special case rules for apostrophe

ex:
You’re lookin’ swell, Dolly.  ->  You’re
smiling’ swell Dolly.

**Comment by multiverse15** [comment]
3 Goals for Release (not counting front-end work):
1. Go with clumsier option of signifying additional terminal punctuation, as limits to re-zombification: colon, semi-colon, and em-dash.
2. Establish stanza patterns for zombified products. 40% one block (as is); 25% quatrains, 20% couplets, 15% tercets (three-line stanzas.) Percentages approximate frequency in contemporary English language poetry.
3. Address odd capitalization, if possible, along with apostrophes.

**Comment by flashashen** [comment]
ill use this issue to address any apostrophe issues. stanzas are in another issue. clumsier option for sentence terminals is done.

**Comment by flashashen** [comment]
possessives are better  now. colloquials are not. one approach would be to adjust the matching regex for mutators to eliminate them from being matched

**Comment by multiverse15** [comment]
This seems issue seems resolved for now.
