### ISSUE TITLE
To do list before May 1:

### ISSUE THREAD

**Issue by multiverse15** [flashashen/zombiepoetryproject#5]
1.   Go with clumsier option of signifying additional terminal punctuation, as limits to re-zombification: colon, semi-colon, and em-dash.
   1.  Establish stanza patterns for zombified products. 40% one block (as is); 25% quatrains, 20% couplets, 15% tercets (three-line stanzas.) Percentages approximate frequency in contemporary English language poetry.
   2.  Address odd capitalization, if possible, along with apostrophes.

**Comment by flashashen** [comment]
maybe we can keep the general conversation leading up to may1 here. That way other issues can be more focused on a particular concern or feature.

**Comment by multiverse15** [comment]
Haha! Sorry! I blitzed him! 

Okay. After a full day of testing, here's what I see addressing before May 1, besides front-end stuff.

It's a short list! And we can work around most if they prove stubborn. As I said last night, we can go live any time!
1. Parentheses in victim text gets expressed in short code in zombie. If this proves problematic, I can always instruct user to purge victim text of parentheses before imput.
2. Random capitalization in zombie text. 
3. Adding potential for stanza divisions.
4. Force zombify short phrases/sentences (roll the die 10 X), then 100% substitution of fragment, if still unchanged.
5. Find some way of ensuring last line of zombie poem doesn't go extremely long or cut off extremely short. (Tie to penultimate line?)

All the other stuff was just spitballin because I was having so much fun...

**Comment by flashashen** [comment]
mike, try installing this in your Chrome browser and then viewing github. it's late days for phase one and i'm just getting acquainted,  but Its a neat add-on

https://chrome.google.com/webstore/detail/zenhub-for-github/ogcgkffhplmphkaahpmffcafajaocjbd?hl=en-US

**Comment by multiverse15** [comment]
Testing tonight was very satisfying. We'll need, I think, to work on the formatting and placement of instructions on Infection Site. Lots of space on right-hand side of page, so perhaps we could move it there? Still can't solve zblog, or even get zombie products to post to zblog, only victim texts post right now.

**Comment by flashashen** [comment]
yes agreed that those need works. each of those could be issues added to todo on the board

**Comment by multiverse15** [comment]
Of the original list of to do: Only #4 remains!

**Comment by flashashen** [comment]
last open issue mentioned here is #10. closing this one.
