### ISSUE TITLE
Zombie poem length

### ISSUE THREAD

**Issue by multiverse15** [flashashen/zombiepoetryproject#6]
We haven't yet incorporated a limit to line number in zombie poems. I think total line length in zombified poem should be from 5-30 lines or so to start, with majority from 14-30. Perhaps a sliding scale?

If the submitted text is less than minimum, presumably program could default to fill out to minimum?

**Comment by flashashen** [comment]
the simplest way to limit is by character count. At the input side we don't know the zombie line delineations yet so won't be able to count. 

Mike, can you clarify how a sliding scale would work? Do you mean to adjust the line length parameters to control the number of lines?

**Comment by multiverse15** [comment]
I guess a sliding scale would depend upon the character count of the victim text. From that total, could we "assign" a maximum number of total zombie lines? Let's say a full "page" of double-spaced prose (standard font and font size) can be estimated at 1600 characters, without spaces. Using that very basic unit of measurement, could we establish a scale of total zombie lines using multiples of this unit? For instance, anything 5 pages (8000 characters) or over would process down to a 28-30-line zombie (the ceiling). 1600 and under would process down to anywhere from 5-24, with a higher percentage falling in the 14-24 range. 1600-4800 would result in 14-30, with most falling within 18-24 lines. These numbers could change, I was just thinking ahead to our stanza patterns: block, couplets, tercets, quatrains...

**Comment by flashashen** [comment]
the two ways to affect line count like this on the server side are listed below. let me
know what is closer to what you had in mind.
1. cut text somewhere in the process, victim text or zombie text. one issue
   with this would be how to select the surviving text when 5 pages is reduced
   to 30 lines worth.
2. lengthening and shortening lines by adjusting the existing parameters
   for the text realizer, ie, min line length and the length threshold where
   it looks for next opportunity to break.

**Comment by flashashen** [comment]
we decided this would be just a character limit on the victim input text. I forget what number we settled on

**Comment by multiverse15** [comment]
1800 characters, I think, which would result in a single-spaced, page-long poem of reasonable line length.

**Comment by flashashen** [comment]
set input char limit to 1800
