### ISSUE TITLE
no indication is given to user when an error occurs talking to nlp server

### ISSUE THREAD

**Issue by flashashen** [flashashen/zombiepoetryproject#7]
some nice try again later message should be displayed. maybe get cute with it.

**Comment by multiverse15** [comment]
Yes! It's inevitable, I guess. Something about needing more brains maybe...braaains.

**Comment by multiverse15** [comment]
First take:
Fortunately, your resistance to the zombie infection is unexpectedly strong...incubation period outside Epi curve parameters. Make the most of the time you have left!

**Comment by multiverse15** [comment]
We could gov'ment it up: Resistance to infection unexpected. Incubation outside Epi parameters. Enjoy the time you have left!

**Comment by flashashen** [comment]
ha i like it. .. when we get to it

**Comment by multiverse15** [comment]
This is either resolved or hasn't been an issue.
