### ISSUE TITLE
Establish stanza patterns for zombified products

### ISSUE THREAD

**Issue by flashashen** [flashashen/zombiepoetryproject#8]
Establish stanza patterns for zombified products. 40% one block (as is); 25% quatrains, 20% couplets, 15% tercets (three-line stanzas.) Percentages approximate frequency in contemporary English language poetry.   - mike

**Comment by flashashen** [comment]
just pushed this up to test. we're at 30, 30, 30, and 10 for no stanza breaks. the line smoothing is also in effect which causes some re-lineation above the re-zombified sentence. the effect doesn't propagate up very far though. a few lines. 

I notice the last stanza is not in correct form. The new re-lineation code could be used to try to get a better result by a trial and error strategy. Mike, let me know if this is a priority.

**Comment by multiverse15** [comment]
Excellent! Already testing. The last stanza question is a good one, and I'm not sure what is best. Probably, it should be a priority a majority of the time, if that makes sense, so if I had to choose, I'd say yes let's try to make the stanza conform. If it's just as easy allow it, say, 15% of the time, to fall where it likes, then that would probably be ideal and more reflective of contemporary practice.

**Comment by flashashen** [comment]
this is done. needed refinements are covered by #10
