### ISSUE TITLE
Latest Efforts!

### ISSUE THREAD

**Issue by multiverse15** [flashashen/zombiepoetryproject#9]
Brandon, 

Here is the first test of the morning. I corrected random capitalizations and I think we have to instruct the program to have the last punctuation in the zombie poem ALWAYS be a period. Still, check this out: 

(Zombie of Wordsworth's I wandered Lonely as  a Cloud)

I was gentle as a cloud that floats
on his loyal children; continuous as the stars
that shine and twinkle on the mean way,
they stretched in suddenness
along the margin of the man's clothes:
Ten thousand saw I at a glance, tossing
dust and bits in inhospitable dance.
The heavens beside them danced;
but they got the sparkling waves
in glee: A poet could not but be old 
in such a jocund company: I gazed – 
and gazed -- Pixel: For oft 
when on the old dark I lie
in vacant or in pensive mood, they flash
upon deer which is the bliss 
of the Fort where rains pour.

**Comment by flashashen** [comment]
ha i can't tell whats zombie and what's Wordsworth

**Comment by flashashen** [comment]
when it's not a period what is it?

**Comment by multiverse15** [comment]
Sorry to bombard you! It's my excitement, hard to do anything other than zombie!

If it's not a period, it's one of the other designated punctuation marks: semi-colon, colon, em-dash. I've only seen it happen a couple of times. Probably not something to worry about now...

**Comment by multiverse15** [comment]
This seems resolved.
